/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
			
				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdlib.h>

int
main(){
/*
 	int previous = 1, next = 2, fib = 0, sum = 2;

	while((previous + next) < 4000000){
		fib = previous + next;
		
		if((fib % 2) == 0){
			sum += fib;
			previous = next;
			next = fib;
		}
	}

	printf("The sum of the even-valued terms in the Fibonacci sequence up to 4000000 is: %d\n", sum);
*/

	int previous = 1, next = 2, sum = 0;

	while(previous < 4000000){
		if((previous & 1) == 0){
			sum += previous;
		}
		next = previous + next;
		previous = next - previous;
	}

	printf("The sum of the even-valued terms in the Fibonacci sequence up to 4000000 is: %d\n", sum);
	
	return 0;
}
